### ISSUE TITLE
About attention visulize

### ISSUE THREAD

**Issue by yuchenWeng** [headacheboy/data-of-multimodal-sarcasm-detection#11]
Hello:
Thanks for your work,  I run the codes and get the attention weight about image，but how can I visulize it, I search a lot, but cant find some useful information.

**Comment by headacheboy** [comment]
Hi, 

It's hard to find my code for visualization now. Sorry for the inconvenience. 

We adapted this [code](https://github.com/abhshkdz/neural-vqa-attention/blob/master/attention_visualization.ipynb). You may find some information in this code.

**Comment by yuchenWeng** [comment]
That OK, thanks a lot
