### ISSUE TITLE
dataset_image.zip数据问题

### ISSUE THREAD

**Issue by 1429904852** [headacheboy/data-of-multimodal-sarcasm-detection#3]
Is there a problem with the dataset_image.zip file? Why does the extraction fail every time?
![2019-12-16 21-58-58屏幕截图](https://user-images.githubusercontent.com/34151761/70912846-c3efcf80-204f-11ea-948e-83b19adbf945.png)
![2019-12-16 22-03-08屏幕截图](https://user-images.githubusercontent.com/34151761/70912887-dcf88080-204f-11ea-9724-bdcb17b8e8c4.png)

**Comment by evanmumu** [comment]
> Is there a problem with the dataset_image.zip file? Why does the extraction fail every time?
> ![2019-12-16 21-58-58屏幕截图](https://user-images.githubusercontent.com/34151761/70912846-c3efcf80-204f-11ea-948e-83b19adbf945.png)
> ![2019-12-16 22-03-08屏幕截图](https://user-images.githubusercontent.com/34151761/70912887-dcf88080-204f-11ea-9724-bdcb17b8e8c4.png)

Where is this compressed package dataset_image.zip, I didn’t find it, please
