### ISSUE TITLE
ResNet-50 V2 extractor question

### ISSUE THREAD

**Issue by 1429904852** [headacheboy/data-of-multimodal-sarcasm-detection#4]
When I got 24636 images after decompression, and then I used ResNet-50 V2 extractor to get 24636 .npy files, the shape of every image feature is [1, 14, 14, 2048], why did I still get errors?

**Comment by headacheboy** [comment]
Hi, 

I'm sorry for my mistake. 

The shape should be [196, 2048]. You can do a reshape first.

**Comment by 1429904852** [comment]
Thanks, It runs successfully.

**Comment by evanmumu** [comment]
> When I got 24636 images after decompression, and then I used ResNet-50 V2 extractor to get 24636 .npy files, the shape of every image feature is [1, 14, 14, 2048], why did I still get errors?

Where can I get these raw image data?
