### ISSUE TITLE
Some images are missing?

### ISSUE THREAD

**Issue by xnyuwang** [headacheboy/data-of-multimodal-sarcasm-detection#5]
We find some images of the training set are missing. Are these images supposed to be missing or something wrong with the uploaded images? If these images are supposed to be missing, how do you process the data without images?

An example of missing images:
910308516510011393
725333760762363905
854334602516733952
904880359350964224
935145326553456641
718073661895249921
851513665983524864
721995610493050880
......

Thanks

**Comment by headacheboy** [comment]
Hello, 

In code/loadData.py:68-89, I discard posts containing several words. Training data do not contain these posts. Therefore, images of these posts are not uploaded. 

Thank you
